config/routes.rb
Rails.application.routes.draw do
  
  devise_for :authors
  root to: 'blog/posts#index'  
 
  # /authors/posts 
  namespace :authors do
    resources :posts do
      put 'publish' => 'posts#publish', on: :member
      put 'unpublish' => 'posts#unpublish', on: :member
      
    end

  end

 resources :comments

  scope module: 'blog' do 
    get 'about' => 'pages#about', as: :about
    get 'contact' => 'pages#contact', as: :contact  
    get 'posts' => 'posts#index', as: :posts
    get 'post/:id' => 'posts#show', as: :post
    # get 'post/:id/comments' => 'comments#show', as: :comments
    # get 'post/:id/comments/new' => 'comments#new', as: :comments_new
    # post 'post/:id/comments' => 'comments#create', as: :create
    # delete 'post/:id/comments/:id' => 'comments#destroy', as: :comment_destroy
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id               :integer          not null, primary key
#  title            :string
#  body             :text
#  description      :text
#  slug             :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  banner_image_url :string
#  author_id        :integer
#

class Post < ApplicationRecord
  acts_as_taggable # Alias for acts_as_taggable_on :tags
  validates :title, presence: true
  validates :body, length: {minimum: 250}, allow_blank: false

  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :author
  has_many :comments

  PER_PAGE = 3

  scope :most_recent, -> { order(published_at: :desc) }
  scope :published, -> { where(published: true) }
  scope :recent_paginated, -> (page) { most_recent.paginate(page: page, per_page: PER_PAGE) }
  scope :with_tag, -> (tag) { tagged_with(tag) if tag.present? }

  scope :list_for, -> (page, tag) do
    recent_paginated(page).with_tag(tag)
  end

  def should_generate_new_friendly_id?
    title_changed?
  end

  def display_day_published
    if published_at.present?
      published_at.strftime('%-b %-d, %Y').to_date
    else
      "Not published yet."
    end
  end

  def publish
    update(published: true, published_at: Time.now)
  end

  def unpublish
    update(published: false, published_at: nil)
  end

  def quoted_id
  self.class.send(:quote_value, @attributes[self.class.primary_key].value_for_database)
  end

end

app/controllers/author/posts_controller.rb
module Author
  
  class PostsController < AuthorController
    before_action :set_post, only: [:show, :edit, :update, :destroy]

    # GET /posts
    # GET /posts.json
    def index
      @posts = Post.most_recent
    end

    # GET /posts/1
    # GET /posts/1.json
    def show
    end

    # GET /posts/new
    def new
      @post = Post.new
    end

    # GET /posts/1/edit
    def edit
    end

    # POST /posts
    # POST /posts.json
    def create
      @post = Post.new(post_params)

      respond_to do |format|
        if @post.save
          format.html { redirect_to @post, notice: 'Post was successfully created.' }
          format.json { render :show, status: :created, location: @post }
        else
          format.html { render :new }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /posts/1
    # PATCH/PUT /posts/1.json
    def update
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to @post, notice: 'Post was successfully updated.' }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /posts/1
    # DELETE /posts/1.json
    def destroy
      @post.destroy
      respond_to do |format|
        format.html { redirect_to author_posts_url, notice: 'Post was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_post
        @post = Post.friendly.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def post_params
        params.require(:post).permit(:title, :body, :description, :banner_image_url)
      end
  end




end

app/controllers/authors/posts_controller.rb
 module Authors
  
  class PostsController < AuthorController
    before_action :set_post, only: [:show, :edit, :update, :destroy, :publish, :unpublish]


    def index
      @posts = current_author.posts.most_recent
    end


    def show
   
      @comments = @post.comments.all
      @comment = Comment.new(post_id: params[:post_id])

    end


    def new
      @post = current_author.posts.new
      @comment = Comment.new(post_id: params[:post_id])

    end


    def edit
    end

    def publish
      @post.publish
      redirect_to authors_posts_url
    end

    def unpublish
      @post.unpublish
      redirect_to authors_posts_url
    end


    def create
      @post = current_author.posts.new(post_params)

      respond_to do |format|
        if @post.save
          format.html { redirect_to authors_post_path(@post), notice: 'Post was successfully created.' }
          format.json { render :show, status: :created, location: @post }
        else
          format.html { render :new }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to authors_post_path(@post), notice: 'Post was successfully updated.' }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @post.destroy
      respond_to do |format|
        format.html { redirect_to authors_posts_url, notice: 'Post was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      def set_post
        @post = current_author.posts.friendly.find(params[:id])
      end

      def post_params
        params.require(:post).permit(:title, :body, :description, :banner_image_url, :tag_list)
      end
  end




end

app/controllers/blog/pages_controller.rb
module Blog
    class PagesController < BlogController
        def about

        end

        def contact
        end
    end
end

app/controllers/blog/posts_controller.rb
module Blog
  
  class PostsController < BlogController


  # GET /posts
  # GET /posts.json
    def index
      @posts = storage.list_for(params[:page], params[:tag])
    end

    # GET /posts/1
    # GET /posts/1.json
    def show
      @post = storage.friendly.find(params[:id])
      @comments = @post.comments.all
      @comment = Comment.new(post_id: params[:post_id])

    end

    private

    def storage
      Post.published
    end


  end

end

app/controllers/blog_controller.rb
 class BlogController < ApplicationController
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/blog/posts/_post.html.erb
<div class="col-sm-6 col-lg-4">
    <div class="card" id="main_posts">
        <div class="card-topper" style='background-image: url(<%= post.banner_image_url %>);'> </div>
        <div class="card-block">
            <h4 class="card-title"><%= link_to post.title, post %></h4>
            <p><%= raw post.tags.map { |t| link_to t.name, posts_path(tag: t.name) }.join(', ') %></p>
            <p class="published-date"><%= t('Published')%> <%= time_ago_in_words(post.display_day_published)

    %></p>
            <p class="published-date">Created by <%= post.author.email %></p>
            <p class="card-text"><%=truncate(post.description, length: 150) %></p>
            <%= link_to 'Read', post, class: 'btn btn-read' %>

            <% if author_signed_in? and current_author.id == post.author_id %>
            <%= link_to 'Edit', edit_authors_post_path(post), class: 'btn btn-read' %>
            <%= link_to 'Delete', authors_post_path(post), method: :delete, data: { confirm: 'Are you sure?'}, class: 'btn btn-read' %>
            <% end %>
        </div>
    </div>
</div>

app/views/blog/posts/index.html.erb
<% provide(:page_title, 'All Posts') %>
<% provide(:blog_active, 'active') %>

<div class="row">
    <%= render @posts %>
</div>
 <div class="apple_pagination">
    <%= will_paginate @posts, container: false %>  
 </div>

 






















 

app/views/blog/posts/show.html.erb
<% provide(:page_title, @post.title) %>
<% provide(:blog_active, 'active') %>

<div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2 text-xs-center">
    <h1><%= @post.title %></h1>
    <p class="author_email"><%= t('Published')%> <%= time_ago_in_words(@post.display_day_published)

    %></p>
    <p class="author_email"><%= @post.author.email %></p>
    <%= @post.body.html_safe %>
    </div>
</div>


<div class="comments col-md-8 offset-md-1 col-lg-6 offset-lg-2 text-xs-center">
  <h3>Comments</h3>
    <% @post.comments.each do |comment| %>
    <div class="comments_style">
      <div class="row comment_email">
        <div class="col">
            <p class="author_email"> Published by <%= comment.email %></p>
        </div>
      </div>
        
      <div class="row comment_content">
        <div class="col-11">
          <p><%= comment.content %></p>
        </div>
        <div class="col-1">
           <% if author_signed_in? %>
             <% if current_author.id == comment.author_id %>
               <i><%= link_to '', comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' }, class: 'fa fa-trash-o btn-trash' %></i>
              <%end%>
           <%end%>
        </div>   
       </div>
    <% end %>
    </div>
      

  <% if author_signed_in? %>
    <div>
      <%=render "/comments/form", post: @post, comment: @comment%>
    </div>
  <% end %>
  
</div>
<div>
  <%= link_to 'Back', posts_path, class: 'btn btn-sm btn-any' %>
</div>