config/routes.rb
Rails.application.routes.draw do
  
  devise_for :authors
  root to: 'blog/posts#index'  
 
  # /authors/posts 
  namespace :authors do
    resources :posts do
      put 'publish' => 'posts#publish', on: :member
      put 'unpublish' => 'posts#unpublish', on: :member
      
    end

  end

 resources :comments

  scope module: 'blog' do 
    get 'about' => 'pages#about', as: :about
    get 'contact' => 'pages#contact', as: :contact  
    get 'posts' => 'posts#index', as: :posts
    get 'post/:id' => 'posts#show', as: :post
    # get 'post/:id/comments' => 'comments#show', as: :comments
    # get 'post/:id/comments/new' => 'comments#new', as: :comments_new
    # post 'post/:id/comments' => 'comments#create', as: :create
    # delete 'post/:id/comments/:id' => 'comments#destroy', as: :comment_destroy
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/author.rb
# == Schema Information
#
# Table name: authors
#
#  id                     :integer          not null, primary key
#  name                   :string
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :comments
  
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id               :integer          not null, primary key
#  title            :string
#  body             :text
#  description      :text
#  slug             :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  banner_image_url :string
#  author_id        :integer
#

class Post < ApplicationRecord
  acts_as_taggable # Alias for acts_as_taggable_on :tags
  validates :title, presence: true
  validates :body, length: {minimum: 250}, allow_blank: false

  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :author
  has_many :comments

  PER_PAGE = 3

  scope :most_recent, -> { order(published_at: :desc) }
  scope :published, -> { where(published: true) }
  scope :recent_paginated, -> (page) { most_recent.paginate(page: page, per_page: PER_PAGE) }
  scope :with_tag, -> (tag) { tagged_with(tag) if tag.present? }

  scope :list_for, -> (page, tag) do
    recent_paginated(page).with_tag(tag)
  end

  def should_generate_new_friendly_id?
    title_changed?
  end

  def display_day_published
    if published_at.present?
      published_at.strftime('%-b %-d, %Y').to_date
    else
      "Not published yet."
    end
  end

  def publish
    update(published: true, published_at: Time.now)
  end

  def unpublish
    update(published: false, published_at: nil)
  end

  def quoted_id
  self.class.send(:quote_value, @attributes[self.class.primary_key].value_for_database)
  end

end

app/controllers/author/posts_controller.rb
module Author
  
  class PostsController < AuthorController
    before_action :set_post, only: [:show, :edit, :update, :destroy]

    # GET /posts
    # GET /posts.json
    def index
      @posts = Post.most_recent
    end

    # GET /posts/1
    # GET /posts/1.json
    def show
    end

    # GET /posts/new
    def new
      @post = Post.new
    end

    # GET /posts/1/edit
    def edit
    end

    # POST /posts
    # POST /posts.json
    def create
      @post = Post.new(post_params)

      respond_to do |format|
        if @post.save
          format.html { redirect_to @post, notice: 'Post was successfully created.' }
          format.json { render :show, status: :created, location: @post }
        else
          format.html { render :new }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /posts/1
    # PATCH/PUT /posts/1.json
    def update
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to @post, notice: 'Post was successfully updated.' }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /posts/1
    # DELETE /posts/1.json
    def destroy
      @post.destroy
      respond_to do |format|
        format.html { redirect_to author_posts_url, notice: 'Post was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_post
        @post = Post.friendly.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def post_params
        params.require(:post).permit(:title, :body, :description, :banner_image_url)
      end
  end




end

app/controllers/author_controller.rb
class AuthorController < ApplicationController 
    before_action :authenticate_author!  
 end

app/controllers/authors/posts_controller.rb
 module Authors
  
  class PostsController < AuthorController
    before_action :set_post, only: [:show, :edit, :update, :destroy, :publish, :unpublish]


    def index
      @posts = current_author.posts.most_recent
    end


    def show
   
      @comments = @post.comments.all
      @comment = Comment.new(post_id: params[:post_id])

    end


    def new
      @post = current_author.posts.new
      @comment = Comment.new(post_id: params[:post_id])

    end


    def edit
    end

    def publish
      @post.publish
      redirect_to authors_posts_url
    end

    def unpublish
      @post.unpublish
      redirect_to authors_posts_url
    end


    def create
      @post = current_author.posts.new(post_params)

      respond_to do |format|
        if @post.save
          format.html { redirect_to authors_post_path(@post), notice: 'Post was successfully created.' }
          format.json { render :show, status: :created, location: @post }
        else
          format.html { render :new }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to authors_post_path(@post), notice: 'Post was successfully updated.' }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @post.destroy
      respond_to do |format|
        format.html { redirect_to authors_posts_url, notice: 'Post was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      def set_post
        @post = current_author.posts.friendly.find(params[:id])
      end

      def post_params
        params.require(:post).permit(:title, :body, :description, :banner_image_url, :tag_list)
      end
  end




end

app/controllers/blog/posts_controller.rb
module Blog
  
  class PostsController < BlogController


  # GET /posts
  # GET /posts.json
    def index
      @posts = storage.list_for(params[:page], params[:tag])
    end

    # GET /posts/1
    # GET /posts/1.json
    def show
      @post = storage.friendly.find(params[:id])
      @comments = @post.comments.all
      @comment = Comment.new(post_id: params[:post_id])

    end

    private

    def storage
      Post.published
    end


  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/authors/posts/_form.html.erb
<%= form_for(post, url: url) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> This post couldn't be saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>  
  <% end %>

  <div class="row">
    <div class="col-md-4">

      <div class="card">
        <div class="card-header">
          <% if @post.new_record? %>
            <h4 class="card-title">New post</h4>
          <% else %>
            <h4 class="card-title">
              <b>Edit</b>
              <span class="thin-text"><%= @post.title %></span>
            </h4>
          <% end %>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            <div class="field">
              <%= f.label :title %>
              <%= f.text_field :title, class: 'form-control' %>
            </div>
          </li>
          <li class="list-group-item">
            <div class="field">
              <%= f.label :banner_image_url %>
              <%= f.text_field :banner_image_url, class: 'form-control' %>
            </div>
          </li>
          <li class="list-group-item">
            <div class="field">
              <%= f.label :description %>
              <%= f.text_area :description, class: 'form-control' %>
            </div>
          </li>
          <li class="list-group-item">
            <div class="field">
              <%= f.label 'Tags' %>
              <%= f.text_area :tag_list, class: 'form-control' %>
            </div>
          </li>
          <li class="list-group-item">
            <div class="actions">
              <%= f.submit "Save blog post", class: 'btn btn-success btn-block' %>

            </div>
          </li>
        </ul>
      </div>

     <div> 
      <% if @post.persisted? %>
        <%= link_to 'Show', @post %> |
      <% end %>
      <%= link_to 'Back', authors_posts_path %>
      </div>


    </div>
    <div class="col-md-8">

      <div class="field">
          <%= f.text_area :body %>
      </div>
    </div>
  </div>




<% end %>

app/views/authors/posts/_post.html.erb
<tr>
    <td><%= link_to post.title, authors_post_path(post) %></td>
    <td></td>
    <% if post.published? %>
        <td><%= link_to 'Unpublish', unpublish_authors_post_path(post), method: :put, class: 'btn btn-sm btn-primary'%> </td>
    <% else %>
        <td><%= link_to 'Publish', publish_authors_post_path(post), method: :put, class: 'btn btn-sm btn-success'%> </td> 
    <% end %>
    <td><%= link_to 'Edit', edit_authors_post_path(post), class: 'btn btn-sm btn-warning'%> </td>
    <td><%= link_to 'Remove', authors_post_path(post), method: :delete, data: { confirm: 'Are you sure?'} , class: 'btn btn-sm btn-danger'%> </td>
</tr>

app/views/authors/posts/edit.html.erb
<% provide(:page_title, "Edit #{@post.title}") %>
<% provide(:author, 'active') %> 


<%= render 'form', post: @post, url: authors_post_url(@post) %>

  

app/views/authors/posts/index.html.erb
<% provide(:page_title, 'All Posts') %>
<% provide(:author, 'active') %>

<div class="row">
  <div style="padding-bottom: 50px;">
    <%= link_to 'New Post', new_authors_post_path, class: 'btn btn-primary btn-lg'%>
  </div>  
  <br>
  <table class="table table-striped">
    <tr>
      <th colspan="5">Title</th>
    </tr>
    <%= render @posts %>
     
  </table>
</div>






















 

app/views/authors/posts/new.html.erb
<% provide(:page_title, 'New Post') %>
<% provide(:author, 'active') %>

<%= render 'form', post: @post, url: authors_posts_url %>

app/views/authors/posts/show.html.erb
<% provide(:page_title, @post.title) %>
<% provide(:author, 'active') %>

<div>
  <td><%= link_to 'Edit', edit_authors_post_path(@post), class: 'btn btn-sm btn-warning'%> </td>
  <%= link_to 'Remove', authors_post_path(@post), method: :delete, data: { confirm: 'Are you sure?'} , class: 'btn btn-sm btn-danger'%>   

</div>
<div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2 text-xs-center">
    <h1><%= @post.title %></h1>
    <% if @post.published? %>
    <div>
    	<p class="author_email"><%= t('Published')%> <%= time_ago_in_words(@post.display_day_published)%></p>
     <br>
        <div><%= link_to 'Unpublish', unpublish_authors_post_path(@post), method: :put, class: 'btn btn-sm btn-primary'%> </div>
    <% else %>
        <div><%= link_to 'Publish', publish_authors_post_path(@post), method: :put, class: 'btn btn-sm btn-success'%> </div> 
    <% end %>
    </div>
     
   

   <br>
    <%= @post.body.html_safe %>
    </div>
</div>