config/routes.rb
Rails.application.routes.draw do
  
  devise_for :authors
  root to: 'blog/posts#index'  
 
  # /authors/posts 
  namespace :authors do
    resources :posts do
      put 'publish' => 'posts#publish', on: :member
      put 'unpublish' => 'posts#unpublish', on: :member
      
    end

  end

 resources :comments

  scope module: 'blog' do 
    get 'about' => 'pages#about', as: :about
    get 'contact' => 'pages#contact', as: :contact  
    get 'posts' => 'posts#index', as: :posts
    get 'post/:id' => 'posts#show', as: :post
    # get 'post/:id/comments' => 'comments#show', as: :comments
    # get 'post/:id/comments/new' => 'comments#new', as: :comments_new
    # post 'post/:id/comments' => 'comments#create', as: :create
    # delete 'post/:id/comments/:id' => 'comments#destroy', as: :comment_destroy
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<br /><br />

<footer>
    <div class="footer" id="footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-2  col-md-2 col-sm-4 col-xs-6">
                    <h3> Specials</h3>
                    <ul>
                        <li> <a href="#"> Product 1</a> </li>
                        <li> <a href="#"> Product 1 </a> </li>
                        
                    </ul>
                </div>
                <div class="col-lg-2  col-md-2 col-sm-4 col-xs-6">
                    <h3> Services </h3>
                    <ul>
                        <li> <a href="#"> Services 1 </a> </li>
                        <li> <a href="#"> Services 2 </a> </li>

                    </ul>
                </div>
                <div class="col-lg-2  col-md-2 col-sm-4 col-xs-6">
                    <h3> About </h3>
                    <ul>
                        <li> <a href="#"> Our Company </a> </li>
                        <li> <a href="#"> About Us </a> </li>
                        <li> <a href="#"> Terms of Services </a> </li>
                        <li> <a href="#"> Our Team </a> </li>
                    </ul>
                </div>
                <div class="col-lg-2  col-md-2 col-sm-4 col-xs-6">
                    <h3> Contact </h3>
                    <ul>
                        <li> <a href="#"> Contact Us </a> </li>
                        <li> <a href="#"> Contact Sales </a> </li>
                        <li> <a href="#"> Contact HR </a> </li>
                        <li> <a href="#"> Contact Admin </a> </li>
                    </ul>
                </div>
                <div class="col-lg-3  col-md-3 col-sm-6 col-xs-12 ">
                    <h3> login or register </h3>
                    <ul>
                        <li>
                            <div>
                                <%= link_to " Log in", new_author_session_path, class: "fa fa-user-plus btn-foot" %>
                            </div>
                        </li>
                        <br>
                        <li>
                             <div>
                                <%= link_to " Register", new_author_registration_path, class: "fa fa-user-plus btn-foot" %>
                            </div>
                        </li>
                    </ul>
                    <ul class="social">
                        <li> <a href="#"> <i class=" fa fa-facebook">   </i> </a> </li>
                        <li> <a href="#"> <i class="fa fa-twitter">   </i> </a> </li>
                        <li> <a href="#"> <i class="fa fa-google-plus">   </i> </a> </li>
                        <li> <a href="#"> <i class="fa fa-pinterest">   </i> </a> </li>
                        <li> <a href="#"> <i class="fa fa-youtube">   </i> </a> </li>
                    </ul>
                </div>
            </div>
            <!--/.row--> 
        </div>
        <!--/.container--> 
    </div>
    <!--/.footer-->

    <!--/.footer-bottom--> 
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class='navbar-brand' href='/'>
      Lili<span class='light'>blog</span>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

    <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <%= link_to 'Blog', root_path, class: "nav-link #{yield(:blog_active)}" %>
      </li>
      <li class="nav-item">
        <%= link_to 'About', about_path, class: "nav-link #{yield(:about_active)}" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Contact', contact_path, class: "nav-link #{yield(:contact_active)}" %>
      </li>
      <% if author_signed_in? %>
          <li class="nav-item">
            <%= link_to 'My Posts', authors_posts_path, class: "nav-link #{yield(:author)}" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Logout', destroy_author_session_path, method: :delete, class: "nav-link" %>
          </li>
          <% else %>
            <li class="nav-item">
            <%= link_to 'Sign Up', new_author_registration_path,  class: "nav-link" %>
            </li>
            <li>
              <%= link_to "Login", new_author_session_path, class: 'nav-link'  %>
            </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
 <!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:page_title)%>  | LiliBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container" <%= controller_name%> <%= action_name %> >

    <%= yield %>

    </div>
  </body>
</html>

app/views/layouts/author.html.erb
 <!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:page_title)%>  | LiliBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cloud.tinymce.com/stable/tinymce.min.js">
      
    </script>
    <meta charset="UTF-8"> <meta name=viewport content="width=device-width, initial-scale=1">


  </head>

  <body>

    <%= render 'layouts/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <div class="container" <%= controller_name %> <%= action_name %> >

    <%= yield %>
     <%= render 'layouts/footer' %>
    </div>
    
  </body>
</html>

app/views/layouts/blog.html.erb
 <!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:page_title)%>  | LiliBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container" <%= controller_name%> <%= action_name %> </div>

    <%= yield %>

    </div>
  </body>
</html>